repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: ["commit-msg"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-docstring-first
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast

  - repo: https://github.com/pre-commit/pygrep-hooks 
    rev: v1.9.0 
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations

  - repo: local
    hooks:
    - id: lint and format
      name: Lint and format files
      entry: make run_lint
      language: system
      types: [python]
    - id: compliance and quality
      name: Run for compliance and quality checks
      entry: make run_compliance
      language: system
      types: [python]
    - id: tests
      name: Run tests
      entry: make run_tests
      language: system
      types: [python]
  

